### ISSUE TITLE
DataBase relationship chart

### ISSUE THREAD

**Issue by thorbuckwel** [SimmeringRook/ProjectHarvest#14]
Use visible analyst and diagram the relationship of the database.

**Comment by SimmeringRook** [comment]
I think one change we discussed (for clarity) was renaming the Recipe_Inventory table to RecipeIngredients?

**Comment by thorbuckwel** [comment]
Alright I will make that change and resubmit the diagram

**Comment by thorbuckwel** [comment]
This is completed however, leaving open until the foreign key composite issue is fixed.

**Comment by thorbuckwel** [comment]
Composite Key issue fixed. Will close after a joint review of the diagram.

**Comment by thorbuckwel** [comment]
Complete there is an error for foreign key not being part of the primary key
