### ISSUE TITLE
HarvestEntites - Try/Catch

### ISSUE THREAD

**Issue by SimmeringRook** [SimmeringRook/ProjectHarvest#18]
Every instance of "using HarvestEntities" needs to be surrounded with Try Catch blocks.

**Comment by SimmeringRook** [comment]
Actually, upon further thought - the form methods that call these Database Helper methods (in the "translator" classes) are the ones that should be wrapped in a try/catch. Any actual handling of the exception should be done at that level (Core will not be able to create MessageBox's to inform the user that something went wrong).

**Comment by thorbuckwel** [comment]
Design was agreed to.
