### ISSUE TITLE
Grocery List Form

### ISSUE THREAD

**Issue by thorbuckwel** [SimmeringRook/ProjectHarvest#32]
Need two button to have coding

- [ ] Save
- [x] Submit

We may be able to do away with the save button if we can get it to save when we build the list.

**Comment by SimmeringRook** [comment]
What are those supposed to do in the context of MVP 1.0?

Submit sounded like it was for updating the Inventory based off what you purchased which was going to be a 1.0.1 or a 1.1 feature.

**Comment by thorbuckwel** [comment]
Yea the submit was to update the inventory. Not sure why we would leave that out of the MVP 1.0 since this would cause the user to go into the inventory to update what they bought. 

Got to thinking about it last night but the Save button should be a Load button. This is so once the user returns from shopping they can pull the list up check what they got then submit.

**Comment by thorbuckwel** [comment]
Will remove the save button.
