### ISSUE TITLE
After planning a meal

### ISSUE THREAD

**Issue by thorbuckwel** [SimmeringRook/ProjectHarvest#33]
Get this error when going back to the tab and then even when trying to open the program again

Additional information: The 'MealEaten' property on 'PlannedMeals' could not be set to a 'System.String' value. You must set this property to a non-null value of type 'System.Boolean'.

**Comment by thorbuckwel** [comment]
Once the meal is cleared from the planned meal table the program runs fine.

**Comment by SimmeringRook** [comment]
I think I made a change in the DB architecture for MealEaten. Let me know what the PlannedMeals.cs file says for you, the one inside HarvestModel.emx
