### ISSUE TITLE
Recipe (Form)

### ISSUE THREAD

**Issue by SimmeringRook** [SimmeringRook/ProjectHarvest#9]
Create form to adding/modifying a recipe.

Add ingredients.

2 Buttons: Ok, cancel

Public property that returns the (modified/created) recipe object.
Public list<Ingredients> that contains each ingredient in the recipe.

**Comment by SimmeringRook** [comment]
HarvestForm (or other utility class) should check the inventory for any non-existent ingredients and create "null" records for them. Then ensure the Recipe_Inventory (rename to RecipeIngredients?) table is creating the ingredient records for the given recipe.

**Comment by thorbuckwel** [comment]
The Form itself is done. It is not connect to the DB as of yet. Need some review, it is doing something strange every time the + button is clicked.

**Comment by SimmeringRook** [comment]
I think I solved the excessive refresh/re-draw of the controls on the "+" click.

**Comment by SimmeringRook** [comment]
Only outstanding task for the form itself is adding the ingredient type combo to the form UI.
